/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FirstPlayNFT__factory } from "./FirstPlayNFT__factory";
export { TetrisNFT__factory } from "./TetrisNFT__factory";
